# Generated by Django 3.2.7 on 2021-09-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Address', models.TextField()),
                ('ZipCode', models.TextField()),
                ('Email', models.TextField()),
            ],
        ),
    ]
